# Generated by Django 2.2.6 on 2019-10-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191011_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-products'),
            preserve_default=False,
        ),
    ]
