# Generated by Django 2.2.6 on 2019-10-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a just giberish discription that we are giving to the model'),
            preserve_default=False,
        ),
    ]
