# Generated by Django 2.2.6 on 2019-10-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
