# Generated by Django 2.2.6 on 2019-10-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=900900789, max_length=90),
            preserve_default=False,
        ),
    ]
